# Generated by Django 4.2.6 on 2023-11-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_item_amount_client_item_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemhistory',
            old_name='item_amount',
            new_name='item_total_amount',
        ),
    ]
