# Generated by Django 4.2.6 on 2023-12-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_itemhistory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='client',
        ),
    ]
